[package]
name = "dpt-lib"
version = "0.1.0"
authors = ["Digital PÄli Tools <digitalpalitools@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
